"""Add tags to Analysis

Revision ID: 6893d35d5952
Revises: fcfb06a8aa56
Create Date: 2026-06-28 17:01:04.817931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6893d35d5952'
down_revision: Union[str, None] = 'fcfb06a8aa56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'tags')
    # ### end Alembic commands ###
